name: Python CVE Scanning

on:
  pull_request:
    paths:
      - 'pyproject.toml'
      - '.github/workflows/cve-scanning.yml'
  push:
    paths:
      - 'pyproject.toml'
      - '.github/workflows/cve-scanning.yml'
    schedule:
      # Run every day at 5am and 5pm
      - cron: '0 5,17 * * *'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.1.11"]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install safety
        run: pip3 install safety
      - name: Run safety check
        run: safety check --full-report -r requirements.txt --policy-file safety-policy.yml
